version: '3.7'

services:
  composer:
    # image: composer
    build:
        context: ./
        dockerfile: ./Dockerfile
    volumes: 
      - ./src:/app
    command: composer install
    # tty: true
